### ISSUE TITLE
loading....

### ISSUE THREAD

**Issue by gerroon** [cryobry/ulauncher-x2goclient#2]
Hi

I installed this ext but it does not seem  to load any sessions. It keeps showing "loading"

I am on Debian, Ulauncher 5.11

![raw](https://user-images.githubusercontent.com/8519469/115638423-037b9b00-a2d8-11eb-95b8-3aaf08196af0.jpeg)

**Comment by cryobry** [comment]
https://github.com/cryobry/ulauncher-x2goclient/pull/1 should fix.
